add bash version check

diff --git a/test-fixtures/ci/get-next-pr-version b/test-fixtures/ci/get-next-pr-version
--- a/test-fixtures/ci/get-next-pr-version
+++ b/test-fixtures/ci/get-next-pr-version
@@ -1,16 +1,29 @@
 #!/usr/bin/env bash
-#
-# Set the release version for PRs run on GitHub Actions.
-#
-# This script performs the following operations:
-#   1. Fetches the list of branches from the remote repository.
-#   2. Filters for branches that follow the 'release/v*' pattern.
-#   3. Strips out any decimal points in version numbers (e.g., converts 'v123.1' to 'v123').
-#   4. Increments the highest version number found by 1 for the next release.
-#   5. Sets a default value if no matching release branches are found.
 
-echo "running main"
+# Script Description:
+# This script is designed to fetch the next version number for a pull request based on the highest version
+# number found in the branch names of a given Git repository. It examines branches prefixed with 'release/v',
+# identifies the highest numerical version, increments it by one, and outputs the next version number for use
+# in automated processes, such as GitHub Actions.
+#
+# Usage:
+# Execute the script directly in a Bash shell. The script prints the next version number to standard output.
+# Example: ./get-next-pr-version.sh
+#
+# Requirements:
+# - Bash version 4.0 or higher due to the usage of associative arrays and other advanced features.
+# - Access to Git and the repository from which to fetch version numbers.
+
 bash --version
+
+echo "********************************"
+echo "*** Bash Version: ${BASH_VERSION[0]}"
+echo "********************************"
+# Check for Bash version 4.0 or above
+if [ "${BASH_VERSINFO[0]}" -lt 4 ]; then
+    echo "Error: Bash version 4.0 or higher is required to run this script."
+    exit 1
+fi
 
 # cat mypipe  > output.txt &
 # cat_pid=$!
